=== cleardemon/ChangeableWorlds-InkScript/JsonSchema/CombatScenario.json
{
	"$schema": "http://json-schema.org/draft-07/schema",
	"$id": "https://changeableworlds.com/json/combat-scenario.json",
	"title": "Combat Scenario",
	"description": "Parameters for engaging the player with other characters in combat.",
	"type": "object",
	"required": [
		"id",
		"environment",
		"phases",
		"resolutions"
	],
	"properties": {
		"id": {
			"type": "string"
		},
		"environment": {
			"type": "object",
			"$ref": "UtilCombatEnvironment.json"
		},
		"phases": {
			"type": "array",
			"uniqueItems": true,
			"items": {
				"type": "object",
				"required": [
					"conditions",
					"resolutions"
				],
				"properties": {
					"npcs": {
						"type": "object",
						"properties": {
							"add": {
								"type": "array",
								"items": {
									"type": "object",
									"required": [
										"npcId",
										"characterId",
										"x",
										"y"
									],
									"properties": {
										"npcId": {
											"type": "string"
										},
										"characterId": {
											"type": "string"
										},
										"x": {
											"type": "integer",
											"minimum": 0,
											"maximum": 255
										},
										"y": {
											"type": "integer",
											"minimum": 0,
											"maximum": 255
										},
										"health": {
											"type": "integer"
										},
										"strength": {
											"type": "integer"
										},
										"fortitude": {
											"type": "integer"
										},
										"avoidance": {
											"type": "integer"
										},
										"effects": {
											"type": "array",
											"uniqueItems": true,
											"items": {
												"type": "string"
											}
										}
									}
								}
							},
							"remove": {
								"type": "array",
								"uniqueItems": true,
								"items": {
									"type": "string"
								}
							}
						}
					},
					"environment": {
						"type": "object",
						"properties": {
							"add": {
								"type": "array",
								"items": {
									"type": "object",
									"required": [
										"type",
										"x",
										"y"
									],
									"properties": {
										"type": {
											"type": "string",
											"enum": [
												"Void",
												"Rock",
												"Tree",
												"Shrub",
												"River",
												"Sea",
												"Wall"
											]
										},
										"x": {
											"type": "integer",
											"minimum": 0,
											"maximum": 255
										},
										"y": {
											"type": "integer",
											"minimum": 0,
											"maximum": 255
										}
									}
								}
							},
							"remove": {
								"type": "array",
								"items": {
									"type": "object",
									"required": [
										"x",
										"y"
									],
									"properties": {
										"x": {
											"type": "integer",
											"minimum": 0,
											"maximum": 255
										},
										"y": {
											"type": "integer",
											"minimum": 0,
											"maximum": 255
										}
									}
								}
							}
						}
					},
					"abilities": {
						"type": "object",
						"required": [],
						"properties": {
							"add": {
								"type": "array",
								"items": {
									"type": "object",
									"required": [
										"id",
										"abilityId"
									],
									"properties": {
										"id": {
											"type": "string"
										},
										"abilityId": {
											"type": "string"
										}
									}
								}
							},
							"remove": {
								"type": "array",
								"items": {
									"type": "object",
									"required": [
										"id",
										"abilityId"
									],
									"properties": {
										"id": {
											"type": "string"
										},
										"abilityId": {
											"type": "string"
										}
									}
								}
							}
						}
					},
					"conditions": {
						"type": "object",
						"required": [
							"win",
							"lose"
						],
						"properties": {
							"win": {
								"type": "array",
								"items": {
									"type": "object",
									"$ref": "UtilCombatCondition.json"
								}
							},
							"lose": {
								"type": "array",
								"items": {
									"type": "object",
									"$ref": "UtilCombatCondition.json"
								}
							}
						}
					},
					"resolutions": {
						"type": "object",
						"$ref": "UtilCombatResolution.json"
					}
				}
			}
		},
		"resolutions": {
			"type": "object",
			"$ref": "UtilCombatResolution.json"
		},
		"modifiers": {
			"type": "object",
			"properties": {
				"normal": {
					"type": "object",
					"$ref": "UtilCombatModifier.json"
				},
				"easy": {
					"type": "object",
					"$ref": "UtilCombatModifier.json"
				},
				"hard": {
					"type": "object",
					"$ref": "UtilCombatModifier.json"
				}
			}
		}
	}
}

=== cleardemon/ChangeableWorlds-InkScript/Json/CombatScenario/TestScenario.json
{
	"id": "scenario-id",
	"environment": {
		"time": "Night",
		"width": 10,
		"height": 10,
		"obstacles": [
			{
				"type": "Void",
				"x": 3,
				"y": 4
			}
		]
	},
	"phases": [
		{
			"npcs": {
				"add": [
					{
						"npcId": "npc-id",
						"characterId": "abc",
						"x": 4,
						"y": 5,
						"health": 30,
						"strength": 20,
						"effects": [
							"abc",
							"def"
						]
					}
				],
				"remove": [
					"npc-id"
				]
			},
			"environment": {
				"add": [
					{
						"type": "Tree",
						"x": 8,
						"y": 9
					}
				],
				"remove": [
					{
						"x": 3,
						"y": 4
					}
				]
			},
			"abilities": {
				"add": [
					{
						"id": "npc-id or PC",
						"abilityId": "abc"
					}
				],
				"remove": [
					{
						"id": "npc-id or PC",
						"abilityId": "abc"
					}
				]
			},
			"conditions": {
				"win": [
					{
						"id": "winConditionId",
						"effects": [
							"effectId"
						],
						"position": [
							{
								"id": "npc-id or PC",
								"x": 1,
								"y": 2
							}
						],
						"action": [
							{
								"abilityId": "id",
								"targetId": "npc-id or PC",
								"x": 3,
								"y": 4
							}
						],
						"stats": [
							{
								"id": "npc-id or PC",
								"type": "Health",
								"equality": "LessThan",
								"value": 20
							}
						]
					}
				],
				"lose": []
			},
			"resolutions": {
				"win": {
					"winConditionId": [],
					"default": [
						{
							"type": "nextPhase"
						},
						{
							"type": "exitCombat"
						},
						{
							"type": "applyEffect",
							"targetId": "npc-id or PC",
							"effectId": "effectId"
						}
					]
				},
				"lose": {
					"loseConditionId": [],
					"default": []
				},
				"retreat": [
					{
						"type": "exitCombat"
					}
				]
			}
		}
	],
	"resolutions": {
		"win": {
			"default": [
				{
					"type": "exitCombat"
				}
			]
		},
		"lose": {
			"default": [
				{
					"type": "exitCombat"
				}
			]
		},
		"retreat": [
			{
				"type": "exitCombat"
			}
		]
	},
	"modifiers": {
		"normal": {
			"multipliers": [
				{
					"targetId": "npc-id",
					"change": 0.8
				}
			],
			"phaseSequence": [ 1, 2, 3, 4 ]
		},
		"easy": {

		},
		"hard": {

		}
	}
}
